%% Generated by lilypond-book
%% Options: [indent=0\mm]
\include "lilypond-book-preamble.ly"


% ****************************************************************
% Start cut-&-pastable-section
% ****************************************************************

#(ly:set-option 'eps-box-padding 3.000000)



\paper {
  indent = 0\mm
}

\layout {
  
}




% ****************************************************************
% ly snippet:
% ****************************************************************
\sourcefileline 12

\header {
  title = "Le Violon de Feu"
  subtitle = \markup { 
    \italic \medium \fontsize #-1 
    "« The soul of fire is displayed on the strings : the secret of the violin is the mastery" 
  }
  subsubtitle = \markup { 
    \italic \medium \fontsize #-1 
    "of bowing styles and bowing epochs of violin composers »" 
  }
}

\layout {
  \context {
    \Score
    % On rend les barres de mesure un peu plus "humaines"
    \override BarLine.hair-thickness = #2.8
    % On utilise des têtes de notes un peu moins "parfaites"
    \override NoteHead.style = #'baroque
    % On désactive la perfection du positionnement
    \override SpacingSpanner.uniform-stretching = ##t
  }
}


\relative c' {
  \key c \major
  \time 4/4
  c4( e g c) | b8( a g f) e2 |
  \bar "|."
}



% ****************************************************************
% end ly snippet
% ****************************************************************
